# デバッグ用
# air(https://github.com/cosmtrek/air) を利用。

FROM golang:1.16.5-alpine

RUN apk update \
  && apk add --no-cache git \
  && go install github.com/cosmtrek/air@latest

WORKDIR /work/webapp
CMD ["air"]
