# デバッグ用
# air(https://github.com/cosmtrek/air) を利用。

FROM golang:1.16.5-alpine

RUN apk update \
  && apk add --no-cache git \
  && apk add --no-cache gcc libc-dev \
  && go install github.com/cosmtrek/air@latest \
  && go get -u golang.org/x/tools/gopls \
  github.com/ramya-rao-a/go-outline

WORKDIR /work/webapp
