FROM golang:1.16.5-alpine as builder

WORKDIR /work/app
COPY ./func .
RUN apk update \
 && apk add --no-cache git \
 && go env -w GOPROXY=direct \
 && go mod download \
 && go build -o /main


FROM alpine:3.14.2
COPY --from=builder /main /main
ENV LOG_LEVEL=2
WORKDIR /

ENTRYPOINT [ "/main"]